variables:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: edrodefeld/oracle
      auto_tag: true
      <<: *docker_creds
    when:
      - event: [push, manual]
        branch: main

  deploy:
    image: bitnami/kubectl
    commands:
      # Oracle is a Job, so we delete the old one and apply the new one
      # Note: You'll need to ensure the Job manifest is available or define it inline here if not in repo
      # Assuming mirage/jobs/oracle.yml exists in THIS repo or we just skip deploy for now if it's managed by cron
      - kubectl delete job oracle -n galaxy || true
      # Only works if the manifest is inside THIS repo (oracle), otherwise you might need a different strategy
      # For now, I'll leave the apply commented out unless you copy the job file into this repo
      # - kubectl apply -f jobs/oracle.yml
    when:
      - event: [push, manual]
        branch: main
