variables:
  - &docker_creds
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: edrodefeld/oracle
      auto_tag: true
      <<: *docker_creds
    when:
      - event: [push, manual]
        branch: main

  deploy:
    image: bitnami/kubectl
    commands:
      - kubectl delete job oracle -n galaxy --ignore-not-found=true
      - kubectl apply -f job.yml
    when:
      - event: [push, manual]
        branch: main
