services:
  web: 
    build:
      context: .
      target: builder
    ports: 
      - '7777:8080'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

networks:
  backend:   
    driver: bridge